# Add config overrides here
# CONFIG_USB_DEVICE_REMOTE_WAKEUP=y
# uncomment to generate bin
CONFIG_BUILD_OUTPUT_UF2=n

CONFIG_CBPRINTF_NANO=y
CONFIG_EXCEPTION_DEBUG=n
CONFIG_RETAINED_MEM_MUTEX_FORCE_DISABLE=y
CONFIG_RETENTION_MUTEX_FORCE_DISABLE=y
CONFIG_RUST_SUPPORTED=n
