manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/petejohanson
    - name: local
      url-base: https://github.com/oN5cZvY1Jj
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: petejohanson
      revision: bootloader/retention-boot-mode-support
      import: app/west.yml
    - name: toprevan-zmk-module
      remote: petejohanson
      revision: main
    - name: ec-support-zmk-module
      # remote: petejohanson
      remote: local
      revision: main
  self:
    path: config
